#!/usr/bin/env sh

NUNCH_SKILLS_QA_SANDBOX="$(mktemp -d "${TMPDIR:-/tmp}/nunch-skills-qa-XXXXXX")"
export NUNCH_SKILLS_QA_SANDBOX
export CODEX_HOME="$NUNCH_SKILLS_QA_SANDBOX/codex"
export CLAUDE_HOME="$NUNCH_SKILLS_QA_SANDBOX/claude"
export CLAUDE_CONFIG_DIR="$CLAUDE_HOME"
export XDG_CONFIG_HOME="$NUNCH_SKILLS_QA_SANDBOX/xdg-config"
export XDG_DATA_HOME="$NUNCH_SKILLS_QA_SANDBOX/xdg-data"
export XDG_CACHE_HOME="$NUNCH_SKILLS_QA_SANDBOX/xdg-cache"
export NUNCH_SKILLS_TELEMETRY_DISABLED=1

mkdir -p "$CODEX_HOME" "$CLAUDE_HOME" "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME"
printf 'Nunch Skills QA sandbox: %s\n' "$NUNCH_SKILLS_QA_SANDBOX"
